### ISSUE TITLE
Оценка

### ISSUE THREAD

**Issue by Lerostre** [WadjetEyeTheSpy/nlp_hw#1]
Прекрасный код, спасибо! По поводу аккураси - шутки шутками, но метод на самом деле не так плох, как может показаться. Бывают такие корпуса текстов, где буквально по одному слову можно понять, релевантный он или нет, например, так что вполне возможная ситуация. У нас такое было на ЛШ (советую кстати съездить, если ещё не, хотя на 3 курсе может быть скучновато), достаточно было найти в тексте "школ", чтобы понять, что речь о школе, тфидф всё равно получше оказался, конечно, а бустинг ещё лучше, но тем не менее

Улучшения. 1. Данные это хорошо, но это не улучшает алгоритм непосредственно. 2. Именованные сущности мб, но что если есть какая-то положительная ассоциация с каким-то именем? 3. Биграммы - полностью согласен. 4. Стопслова - это то, к чему я тоже пришёл впоследствии. Не люблю их убирать как раз по этой причине - всякие отрицания меняют тональность кардинально, но являются стопсловами. Только реализации этого всего не хватает (-1)

9

**Comment by Lerostre** [comment]
Кстати интересно, а лучше ли нейросети парсят, чем люди, или ещё нет?..

### По коду
Конвертация тегов и вообще всего очень красиво делается через `map` и ему аналогичные в пандасе и любой уважаемой библиотеке, например
```
d = {"A": "B", "B": "C"}
l = ["B", "A"]
print(*map(d.get, l))
# C, B
```
Функциональное программирование это настоящая магия...

Чанкер. Не надо искать слово по индексу, лучше брать сразу 2:
```for i in range(0, len(your_list)-1):
         window = your_list[i: i+(n-1)] # n - сколько слов хочешь взять
```
Индексация в списке дорогая по времени, про это следующий курс. А ещё можно это же окно сразу же разметить мапом и доставать тег-паттерны просто по щелчку пальцев, вот как всё связано оказывается

Но в целом всё просто чудесно, не хочу ни к чему придираться, кроме отсутствия последней части, ну там же немного совсем (
9

**Comment by WadjetEyeTheSpy** [comment]
Большое спасибо, это ужасно _(ужасающе? невероятно? \*insert любая усилительная штука*)_ полезный фидбэк!
